src/tsplugins/tsplugin_timeref.cpp
For the plugin `timeref` the parameter `--start` has now a new predefined value `"system"`. This value will read the system clock and uses it.
=> timeref: Add support for --start "system"

src/libtsduck/tsDektecInputPlugin.cpp, src/libtsduck/tsVersion.h, src/tsplugins/tsplugin_zap.cpp
This fixes a bug with the Dektec input plugin that prevented it from being used.  The timeout-related option is named "receive-timeout", yet it was expecting an option named "timeout".  Now, it expects an option named "receive-timeout".
Signed-off-by: Aaron Levinson <alevinsn_dev@levland.net>
=> DektecInputPlugin:  fix bug and add feature; Zap plugin:  add feature

src/libtsduck/tsPlatform.h
This commit adds support for aarch64 (aka ARM64).
The memory barier copied from here: https://github.com/mirage/shared-memory-ring/blob/master/lib/barrier.h#L32
=> tsPlatform: add support for aarch64

src/libtsduck/tsPlatform.h
This commit adds support for MIPS architecture.
The memory barier copied from here: https://www.linux-mips.org/archives/linux-mips/2015-06/msg00020.html
Although it seems that a more generic approach is this one? https://stackoverflow.com/questions/14950614/working-of-asm-volatile-memory
Tested using OpenEmbedded build system on a mipsel linux dvb box.
Related #173, #172
=> tsPlatform: add support for MIPS architecture

src/tsplugins/tsplugin_limit.cpp
Changes:
- Add a new threshold to split audio & video behaviour.
- The thresholds2 & thresholds3 only applies to audio/video packets in the pid list.
- The value "0" in the threshold disables the check (except for the last threshold).
- Some additional checks added.
=> Enhancements of limit plugin

src/libtsduck/windows/tsDirectShowUtils.cpp, src/tsplugins/tsplugin_dvb.cpp
I can't test actual reception yet, but I've verified that my code looks up the frequency and gets the corresponding physical channel so I'm confident it will work from my tests last weekend when the laptop was in a reception area.
However, the "--hf-band-region" does not appear to work for the tsp command, so it mapped frequency 207000000 to channel 9 which would I think be the VHF channel for Europe.
=> Atsc tuning fixes

src/doc/building.md, src/libtsduck/tsVersion.h
I updated a description in building.md regarding tools required for building on macOS.
When I tried to build tsduck on macOS, I got the following messages:
```
/Users/masnagam/workspace/tsduck/build/build-project-files.sh: line 268: unix2dos: command not found
/Users/masnagam/workspace/tsduck/build/build-project-files.sh: line 267: unix2dos: command not found
```
The messages can be eliminated by installing `dos2unix` like below:
```console
brew install dos2unix
```
=> `dos2unix` is required for building on macOS

src/libtsduck/tsUString.cpp
Code points between U+8000 and U+FFFF are encoded using 3 octets in
UTF-8.
=> Correct the maximum buffer size of a UTF-8 string

src/tsplugins/tsplugin_mux.cpp
Replicate new "--set-label" and "--reset-label" options from "remap/duplicate" to the "mux" plugin.
=> Add target label support to mux plugin

src/libtsduck/tsPacketizer.cpp, src/libtsduck/tsVersion.h
Since 'all warnings being treated as errors' GCC 4.8 complains about memset with zero bytes length and compilation fails. Skipping memset when remain_in_packet is zero fixed the issue.
Fixes #363.
=> Fix memset warning when bytes length is zero

src/libtsduck/tsVersion.h, src/libtsduck/tsxmlElement.h, src/libtsduck/tsxmlElementTemplate.h
As an Ubuntu 18.04 user I eventually ran into #219. Here is my `gcc --version` output:
```
$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I know that the workaround of using GCC version other than 6 and 7 seems OK but it looks an interesting issue to solve. I tried to dig into it but didn't find a proper solution except to skip the method that causes the error. Since this method is overloaded, client code will rely on them. WDYT?
I ran the test suite and it seemed fine:
```
$ make -j8 NOPCSC=1 NODTAPI=1
$ source ./src/utest/release-x86_64/setenv.sh …
```
=> Skip method that causes GCC template substitution error

build/msvc/libtsduck-files.props, build/msvc/libtsduck-filters.props, build/qtcreator/libtsduck/libtsduck-files.pri, src/libtsduck/private/tsRefType.h, src/libtsduck/tsMPEG.h, src/libtsduck/tsSkyLogicalChannelNumberDescriptor.cpp, src/libtsduck/tsSkyLogicalChannelNumberDescriptor.h, src/libtsduck/tsTables.h, src/libtsduck/tsVersion.h, src/libtsduck/tsduck.h, src/libtsduck/tsduck.names, src/libtsduck/tsduck.tables.model.xml
This descriptor has tag 0xB1 and follow a BskyB private_data_specifier.
I'm currently searching the structure of the 0xB2 (aka bskyb_service_descriptor) on the net but cannot find anything useful apart from a "category byte". If someone has informations about it I am willing to integrate it to TSDuck...
Anthony Delannoy
=> Add bskyb_logical_number descriptor

Makefile.tsduck, src/libtsduck/base/network/tsSRTSocket.cpp, src/libtsduck/tsVersion.h, src/libtsduck/tsduck.mk
I made two small changes:
* always set messageapi option. It is true by default and we need to be able to turn it off if we want.
* check for locally compiled/installed libsrt in /usr/local/include for NOSRT setting
=> Small libsrt changes

src/libtsduck/base/network/tsSRTSocket.cpp, src/libtsduck/tsVersion.h
srt_socket deprecated since commit eef66e53 and replaced by
srt_create_socket.
=> libsrt: update after srt_socket deprecation

src/libtsduck/base/tsPlatform.h, src/libtsduck/dtv/linux/tsDTVProperties.h, src/libtsduck/dtv/linux/tsTunerGuts.cpp, src/libtsduck/dtv/tsDeliverySystem.h, src/libtsduck/dtv/tsModulation.h
Restore compatbility with some legacy kernels (linux 3.2) because some missing declarations.
=> Kernel legacy compatibility 

src/libtsduck/dtv/tsPESDemux.cpp
Only the first SEI was parsed, this PR would allow the pes filter to parse all of them.
=> Parse all SEI even if there are more than one in a NALU

src/tsplugins/tsplugin_spliceinject.cpp
The aim of this PR is to inject time_signal 4s before pts_time instead of right at the beginning.
The spliceinject filter options used are : -P spliceinject --service 1545  --inject-count 1 --files '/tmp/splices000.xml' --wait-first-batch
splices000.xml contained this : 
```
<splice_information_table>
<time_signal pts_time="6957864362" />
<splice_segmentation_descriptor segmentation_event_id="100" segmentation_type_id="0x24" segment_num="1" segments_expected="1">
<segmentation_upid type="0"/>
</splice_segmentation_descriptor>
</splice_information_table>
```
=> Inject time signal at specific time using splice time and start delay

src/libtsduck/dtv/tsContinuityAnalyzer.cpp, src/libtsduck/dtv/tsContinuityAnalyzer.h
Rather than expose PIDState, I opted to just expose the per-PID duplicate count and last packet.  There were already methods for exposing the first and last CCs.
The enablement of the copy constructor is needed for forward packet CC analysis without affecting the "main" ContinuityCounter object for a stream.
=> Protected2 and copy constructor continuity analyzer

src/libtsduck/dtv/windows/tsDirectShowNetworkType.cpp
This code was from an earlier contribution of mine, but it was a mistake. 
It caused to some DVB-C tuners to indicate support for ATSC.
Within two years we weren't able to find any user having one of the rare ClearQam tuners, so I can't say how these behave and can be identified. At least, not like this.
=> Don't detect digital cable as ATSC

src/libtsduck/dtv/tsModulationArgs.cpp, src/libtsduck/dtv/tsTSScanner.cpp, src/tstools/tsscan.cpp
The issue related with incorrect transmission parameters with some ISDB-T tuners (last posts on #24)
`tsscan` and libtsduck/dtv/tsModulationArgs.cpp
This series of commits provide a fix for the invalid modulation parameters with some ISDB-T tuners.
Basically this solution:
- Uses TSScanner to retrieve the modulation parameters that should be displayed.
- Inside TSScanner, do the tuning parameters query as late as possible to give the device some time to update its internal status.
- Corrects the enumeration used for displaying per-layer constellation types.
- Checks the validity of some parameters before showing them.
- Fixes some typos with the displayed data.
=> tsscan: Display modulation parameters for ISDB-T broadcasts.

src/libtsduck/base/network/tsSRTSocket.cpp, src/libtsduck/tsVersion.h
A missing initialization on `int *addrlen` of srt_accept() cause a bad
paremeters error (SRT_EINVPARAM).
This error seems to have no consequences until libsrt >= 1.4.2
See: https://github.com/tsduck/tsduck/issues/738
See: https://github.com/Haivision/srt/blob/master/docs/API-functions.md#srt_accept
=> Fix bad parameters issue on srt_accept()

build/install-prerequisites.sh
E.G. centos Stream 8 will be 899 All other releases contain proper minor revisions and thus igore the trailing .99
=> Detect Centos Stream as minor version 99.

src/libtsduck/dektec/private/tsDVBT2ParamsEvaluator.cpp, src/libtsduck/dektec/tsDektecOutputPlugin.cpp, src/libtsduck/dektec/tsDektecOutputPlugin.h
Hi,
There are 2 patches here, first:
I personally need to stream DVB-T .ts files on bandwidth 8MHz, but wanted to have the rest parameters calculated with "input modulation". I went a step further, so that the user can specify any combination of the four parameters used for bitrate evaluation and the algorithm will choose the best one matching user's needs.
The second patch only touches my recent addition of "input-modulation" for DVB-T2 to make it slightly faster at the cost of precision. My initial implementation turned out needlessly too aggressive for everyday use.
=> Input modulation improvements

src/libtsduck/base/algo/tsMessageQueueTemplate.h, src/libtsduck/base/report/tsReportFileTemplate.h, src/libtsduck/base/system/tsResidentBufferTemplate.h, src/libtsduck/base/types/tsFloatingPoint.h, src/libtsduck/base/types/tsSafePtrTemplate.h, src/libtsduck/base/types/tsVariableTemplate.h, src/libtsduck/crypto/tsCipherChainingTemplate.h
When using TSDuck from a C++20 application, the headers throw various
errors. This commit tidies them up.
The library itself still does not build cleanly as C++20 (biggest problem is the
initialisation of the const TSPacket instances in tsTSPacket.c) however this is enough for 
Various types in libtsduck
Most changes are removing the template arguments from destructors. These redundant arguments cause warnings (which frequently become errors) when building a C++20 target
There's also a change to `operator==(NUM_T x1, const ts::FloatingPoint<FLOAT_T,PREC>& x2)`  because C++20 seems to reorder operator arguments, which causes the original implementation of this to become in infinite loop (again, this caused a compiler warning which became an error) - the fix is to explicitly call the …
=> Allow Headers To Be Used From C++20 Code

src/libtsduck/dtv/t2mi/tsT2MIDemux.cpp
T2-MI plugin (`t2mi`)
Tiny optimization, reusing the previously determined T2-MI packet size.
=> Reuse T2-MI packet size

src/libtsduck/config/tsduck.names
…ding to ITU-T H.222.0 (2021-06) and DVB drafts of ETSI EN 300 468 and ETSI TS 101 154
=> add metadata for next generation video codecs (VVC, AVS3 & EVC) according tp latest industry standards

src/libtsduck/dtv/descriptors/tsAVS3VideoDescriptor.cpp, src/libtsduck/dtv/descriptors/tsAVS3VideoDescriptor.h, src/libtsduck/dtv/descriptors/tsDVBVVCSubpicturesDescriptor.cpp
AVS3 - stricter checking on values parsed from XML
VVC - use descriptor name "vvc_subpictures_descriptor" as defined in EN 300 468
=> Updates to AVS3 and VVC codecs

src/libtsduck/config/Makefile
This fixes a regression in eb8e5425afef47b9bbc4c815f9c071194127166d and amends b5eeb6787fd2ed23908d8d173099afbc40df8a6c.
Fixes https://github.com/tsduck/tsduck/issues/1111
#1111 
dectek.names
Fix build with python3 and no binary named "python".
=> Make sure python3 is used in makefiles

src/tsplugins/tsplugin_svresync.cpp
Add support for the edge case when the PCR is inside an independent pid. Fixes #1095.
=> Fix svresync plugin with independent PCR pid

src/libtsduck/plugins/plugins/tshlsOutputPlugin.cpp, src/libtsduck/plugins/plugins/tshlsOutputPlugin.h
This implements in the "HLS output" a new parameter called "--slice-only".
Related to #1125
=> HLS output: new "--slice-only" option

scripts/install-wintools/install-java.ps1
The AdoptOpenJDK API has been deprecated for some time in favour of the Eclipse Temurin API
=> migrate from AdoptOpenJDK API to Adoptium

src/libtsduck/plugins/plugins/tsRISTInputPlugin.cpp, src/libtsduck/plugins/plugins/tsRISTOutputPlugin.cpp
Changed a reference to a correct external library.
* tsRISTInputPlugin
* tsRISTOutputPlugin
RIST plugins have a comment that refers to an external dependancy libsrt. Corrected that to librist.
Since the changes are in code comments, there are no functional changes and thus no test were run.
=> Corrections in RIST plugins' comments

src/libtsduck/dtv/pes/tsPESDemux.cpp, src/libtsduck/tsVersion.h
When processing the second TS packet onwards of a PES unit, the PESDemux component will check to see if it has a complete packet, and invoke the handler. When the PES unit fits within a single TS packet, this means the check is not performed, and the handler is not invoked until the start of the next unit, which flushes out the pending one.
This commit adds a length check to the path taken by the first packet, so payloads made of a single TS packet are released in a timely manner.
An example of when you might find such a packet is subtitles, where an empty page (to clear the screen) could easily fit within a single packet.
#1232 
PESDemux
Check the length of the PES unit in the first TS packet as well as subsequent ones, so single-packet PES units are correctly handled
=> PESDemux: Check payload length of single-packet PES units

Makefile
Not really. Although I believe the typos being fixed here were introduced while fixing #1229.
Makefile
My editor showed somewhat wonky syntax highlighting of _Makefile_. That lead to finding missing `'`s in targets _deb-tools-control_ and _deb-dev-control_.
Running those targets directly (with some local workarounds due to not-quite-appropriate environment for them) resulted in
```
bash: -c: line 8: unexpected EOF while looking for matching `''
```
I believe running `make NOPCSC=1 deb` would show an error in an appropriate environment.
=> Fix typos in Makefile leading to (syntax) error

Makefile, src/libtsduck/config/Makefile
Closes #1305 
libtsduck pkg-config will now output `--std=c++14` and `--std=c++20` when compiled with `CXXFLAG_STANDARD=-std=c++14` and `CXXFLAG_STANDARD=-std=c++20`, respectively.
* Updates the package-config file to use a placeholder instead of a literal flag
* Updates the libtsduck makefile to replace the placeholder with the flag as set by make
=> update libtsduck pkg-config to respect makevar CXXFLAGS_STANDARD

src/libtsduck/dtv/epg/tsEITGenerator.cpp, src/libtsduck/dtv/epg/tsEITOptions.h, src/libtsduck/dtv/signalization/tsSectionFileArgs.cpp, src/tsplugins/tsplugin_eitinject.cpp, src/tstools/tseit.cpp
The current options for EITGenerator only allow to select either actual or other, and either pf or schedule. You have no way for instance to select actual pf, other pf and actual shedule but not other schedule. However this is what you are supposed to do on eg. the French DTT.
EITGenerator, eitinject tsp plug-in and tseit application.
This commit makes 4 distinct options, one for each kind. It does however change the CLI of tsp and tseit. I am unsure what the policy of the project is regarding such changes, so apply with caution.
=> EIT: change options to independantly select the 4 kinds

src/libtsduck/base/network/tsSRTSocket.cpp
tsSRTSocket.cpp
Added all the available stats in [srt sastistics](https://github.com/Haivision/srt/blob/master/docs/API/statistics.md#srt-statistics)
Note:
I think the keys of the json object should be named with theoriginal srt name of the stastistic. i.e:
`root.query(u"receive.total", true).add(u"bytes", stats.byteRecvTotal);`
should be 
`root.query(u"receive.total", true).add(u"byteRecvTotal", stats.byteRecvTotal);`
to let the end-user identify the specific stat needed.
This merge is only for the json output
=> Compleate Srt statistics for json output 

src/libtsduck/base/network/tsWebRequest.cpp, src/libtsduck/base/network/tsWebRequest.h, src/libtsduck/base/network/tsWebRequestArgs.cpp, src/libtsduck/base/network/tsWebRequestArgs.h, src/libtsduck/base/unix/tsWebRequestGuts.cpp
http (input) plugin
add support for retrieving compressed content
=> Add support for --compressed option using libcurl

src/libtsduck/dtv/descriptors/tsS2Xv2SatelliteDeliverySystemDescriptor.h
Update tsS2Xv2SatelliteDeliverySystemDescriptor.h
tsS2Xv2SatelliteDeliverySystemDescriptor.h
Incorrect initializer used
=> Fix member initialization

src/libtsduck/base/network/tsWebRequest.cpp, src/libtsduck/base/network/tsWebRequestArgs.cpp, src/libtsduck/base/network/tsWebRequestArgs.h
HLS / HTTP input
Allow the user to set custom header/s in HTTP requests - I added this because a particular HLS stream I needed to ingest was using a custom token-based authentication scheme.
Example usage:
```
tsp -I hls --headers 'x-affiliate-auth-key: {token}' https://{url}/index.m3u8 -O file  /tmp/test.mp4
```
Several headers can be added with multiple `--headers` entries.
=> Add support for custom HTTP headers in HTTP/HLS communications

src/libtsduck/dtv/descriptors/dvb/tsURILinkageDescriptor.cpp, src/libtsduck/dtv/descriptors/dvb/tsURILinkageDescriptor.h, src/libtsduck/dtv/descriptors/dvb/tsURILinkageDescriptor.names, src/libtsduck/dtv/descriptors/dvb/tsURILinkageDescriptor.xml, src/libtsduck/tsVersion.h
DVB URI Linkage Descriptor
For URI Linkage Descriptor used with DVB-I (uri_linkage_type=0x03) parse the private_data according to DVB Bluebook A177 / ETSI TS 103 770
=> parse DVB-I info in URI linkage descriptor

src/libtsduck/dtv/epg/tsEITGenerator.cpp
Events that last several hours could be discarded by the rule "segment end in the past", because events are only put in segments according to their start date.
=> epg: do not discard events if they are still running

.github/workflows/code-coverage.yml
No related issue
github actions workflows
Code coverage reports are useful for adding new tests and finding bugs. In some cases, it is easier to download a report from github than running it locally (proposed workflow uploads coverage reports as github artifact). Also, it might be useful for new pull requests to decide whether more tests required.
You can see the report and workflow execution here: https://github.com/svlobanov/tsduck/actions/runs/7426865570
=> Add code coverage reports generation

src/libtsduck/dtv/signalization/tsTablesLogger.cpp
This patch fixes heap buffer overflow found in handleInvalidSection() by AddressSanitizer in test-002. Also it fixes handleInvalidSection behavior when mpeg_sect CRC32 is correct.
Fixed heap overflow:
ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61600000718e at pc 0x7f294980c220 bp 0x7ffdb416a7d0 sp 0x7ffdb416a7c8 READ of size 1 at 0x61600000718e thread T0
#0 0x7f294980c21f in ts::GetUInt32BE(void const*) base/types/tsMemory.cpp:173
#1 0x7f2949e136dd in ts::GetUInt32(void const*) base/types/tsMemory.h:335
#2 0x7f2949e136dd in ts::TablesLogger::handleInvalidSection(ts::SectionDemux&, ts::DemuxedData const&) dtv/signalization/tsTablesLogger.cpp:818
#3 0x7f2949b73605 in ts::SectionDemux::processPacket(ts::TSPacket const&) dtv/demux/tsSectionDemux.cpp:528
#4 0x7f2949b73de4 in …
=> Fixed heap buffer overflow and invalid behaviour in handleInvalidSection

src/libtsduck/dtv/descriptors/dvb/tsURILinkageDescriptor.cpp, src/libtsduck/dtv/descriptors/dvb/tsURILinkageDescriptor.h, src/libtsduck/dtv/descriptors/dvb/tsURILinkageDescriptor.xml, src/libtsduck/tsVersion.h
None
all
Recent update to DVB-I (DVB Bluebook A177r6 - expected to be ETSI TS 103 770 v1.2.1) allows private data as additional trailing bytes in the DVB-I Info() - for backward compatability purposes.
=> allow private data in URI Linkage Descriptor for DVB-I

Makefile.inc, src/tsplugins/tsplugin_pcrcopy.cpp
no related issue
pcrcopy plugin
If --reference-label is not set by user, then _ref_label sets to 32 (TSPacketLabelSet::MAX+1)
by ts::PCRCopyPlugin::getOptions().
ts::PCRCopyPlugin::processPacket() calls pkt_data.hasLabel(_ref_label) that calls
CompactBitSet::test() that uses 'int_t(1)<<pos' code, where int_t is uint32_t and pos=32
1<<32 is undefined by C++ standard for 32-bit unsinged integer. In real world 1<<32 usually
equals to 1 so it means that pkt_data.hasLabel(32) is equal to pkt_data.hasLabel(0)
Real issue can be caused by the following command (reproduces on macos arm64 clang-15 and
linux x86_64 gcc-12):
~~~
% tsp --verbose -I file ../tsduck-test/input/test-092.ts -P filter -p 0x140 --set-label 0 -P pcrcopy -r 0x78 -t 0x82 -O drop
* file: initial input bitrate is 24,047,795 b/s
* …
=> Fixed undefined behaviour in pcrcopy plugin that cause real issue with label processing

src/libtsduck/base/cpp/tsPlatform.h, src/libtsduck/base/system/tsSysInfo.cpp
utest and tsduck-test tests are passed (if compiler is clang-16)
Verified on Ubuntu 23.10, clang 16.0.6 (make LLVM=1) Currently there are some issues if compiler is gcc-13 (more info #1418).
Currently S390X is the only supported big-endian architecture by generic Linux distros so it might be useful to test tsduck on BE platform.
There are several ways how to develop for s390x without buying IBM mainframes: https://docs.gitlab.com/omnibus/development/s390x.html
~~~
$ tsp --version=all
tsp: TSDuck - The MPEG Transport Stream Toolkit - version 3.37-3606 Built Jan 15 2024 - 09:45:54
Using Clang 16.0.6 (15), C++ std 2017.03
System: Ubuntu (Ubuntu 23.10), on S390X, 64-bit, big-endian, page size: 4096 bytes Acceleration: CRC32: no, AES: no, SHA-1: no, SHA-256: no, SHA-512: no Bitrate: 64-bit …
=> Added S390X platform support

src/libtsduck/dtv/descriptors/dvb/tsDVBServiceProminenceDescriptor.cpp
Small update to the printout of the DVB Service Prominence Descriptor to more clearly indicate that target regions are part of eash service.
=> indent the target reqion information for a siganlled service

src/libtsduck/dtv/descriptors/dvb/tsComponentDescriptor.names, src/libtsduck/dtv/descriptors/uwa/tsUWAVideoStreamDescriptor.cpp, src/libtsduck/dtv/descriptors/uwa/tsUWAVideoStreamDescriptor.h, src/libtsduck/dtv/descriptors/uwa/tsUWAVideoStreamDescriptor.names, src/libtsduck/dtv/descriptors/uwa/tsUWAVideoStreamDescriptor.xml, src/libtsduck/dtv/signalization/tsPSI.cpp, src/libtsduck/dtv/signalization/tsPSI.h, src/libtsduck/dtv/signalization/tsPSI.names
T/UWA 005-2.1 is the signalling specification defining different carriage mechanisms for HDR Vivid dynamic metadata. This PR adds support for the descriptor which provides HDR Vivid version information and the value for signalling HDR Vivid in a DVB Component descriptor.
=> Add the HDR Vivid vfrom UHD World Association (see T/UWA 005)

src/libtsduck/dtv/signalization/tsPSI.cpp
Confirmed the stream_type values for VVC according to ISO/IEC 13818-1:2023 (9th edition - https://www.iso.org/standard/87619.html) and H.222.0 v9 (08/23 - https://www.itu.int/itu-t/recommendations/rec.aspx?rec=15655&lang=en)
Remove the health warding on non-confirmed values for `ST_VVC_VIDEO` and `ST_VVC_VIDEO_SUBSET`
=> Confirmed stream_type values for VVC

src/libtsduck/dtv/descriptors/dvb/tsAACDescriptor.cpp, src/libtsduck/dtv/descriptors/dvb/tsAACDescriptor.h, src/libtsduck/dtv/descriptors/dvb/tsAACDescriptor.xml
Updates the `AAC_descriptor` from [ETSI EN 300 468 v1.18.1](https://www.etsi.org/deliver/etsi_en/300400_300499/300468/01.18.01_60/en_300468v011801p.pdf) which does not allow the `AAC_type` or `additional_info_byte`(s) to be specified unless the `SAOC_DE_flag` is present
````
Table H.1: AAC descriptor
+---------------------------------+---------+------------+
| Syntax                          | Number  | Identifier |
|                                 | of bits |            |
+---------------------------------+---------+------------+
|AAC_descriptor() {               |         |            |
|   descriptor_tag                |    8    | uimsbf     |
|   descriptor_length             |    8    | uimsbf     |
|   profile_and_level             |    8    | uimsbf     |
|   if (descriptor_length …
```
=> Update the DVB AAC descriptor to be more aligned with EN 300 468

src/libtsduck/base/xml/tsxmlElement.h, src/libtsduck/dtv/descriptors/dvb/tsSupplementaryAudioDescriptor.cpp, src/libtsduck/dtv/descriptors/dvb/tsSupplementaryAudioDescriptor.h, src/libtsduck/dtv/descriptors/dvb/tsSupplementaryAudioDescriptor.names
Use std::optional for optional values in the Supplementary Audio Descriptor
=> use std::optional for optional values in Supplmentary Audio Descriptor

src/libtsduck/base/cpp/tsPlatform.h, src/libtsduck/dtv/codec/tsCodecType.cpp, src/libtsduck/dtv/codec/tsCodecType.h, src/libtsduck/dtv/descriptors/avs/notes.txt, src/libtsduck/dtv/descriptors/avs/tsAVS2AudioDescriptor.adoc, src/libtsduck/dtv/descriptors/avs/tsAVS2AudioDescriptor.cpp, src/libtsduck/dtv/descriptors/avs/tsAVS2AudioDescriptor.h, src/libtsduck/dtv/descriptors/avs/tsAVS2AudioDescriptor.names, src/libtsduck/dtv/descriptors/avs/tsAVS2AudioDescriptor.xml, src/libtsduck/dtv/descriptors/avs/tsAVS3AudioDescriptor.adoc, src/libtsduck/dtv/descriptors/avs/tsAVS3AudioDescriptor.cpp, src/libtsduck/dtv/descriptors/avs/tsAVS3AudioDescriptor.h, src/libtsduck/dtv/descriptors/avs/tsAVS3AudioDescriptor.names, src/libtsduck/dtv/descriptors/avs/tsAVS3AudioDescriptor.xml, src/libtsduck/dtv/descriptors/avs/tsAVS3VideoDescriptor.cpp, src/libtsduck/dtv/descriptors/avs/tsAVSANCDataBlockType.arch-cpp, src/libtsduck/dtv/descriptors/avs/tsAVSANCDataBlockType.arch-h, src/libtsduck/dtv/descriptors/avs/tsAVSANCDataBlockType.arch-names, src/libtsduck/dtv/signalization/tsPSI.cpp, src/libtsduck/dtv/signalization/tsPSI.h, src/libtsduck/dtv/signalization/tsPSI.names, src/libtsduck/dtv/tables/mpeg/tsPMT.cpp
These descriptors indicate the characteristics of AVS2 and AVS3 coded audio in an elementary stream. They are defined in T/AI 109/7
=> Add AVS audio descriptors from T/AI 109.7

src/libtsduck/dtv/codec/tsCodecType.cpp, src/libtsduck/dtv/signalization/tsPSI.cpp, src/libtsduck/dtv/signalization/tsPSI.h, src/libtsduck/dtv/signalization/tsPSI.names
Couple of updates for AVS2/AVS3 codecs relate to checking content type
Update to use a set lookup, rather than a large switch statement to determine Audio/Video/Subtitling
=> Small updates related to AVS codecs and codec types

src/libtsduck/dtv/descriptors/dvb/tsCPCMDeliverySignallingDescriptor.cpp, src/libtsduck/dtv/descriptors/dvb/tsLocalTimeOffsetDescriptor.cpp, src/libtsduck/dtv/descriptors/isdb/tsSIParameterDescriptor.cpp, src/libtsduck/dtv/descriptors/isdb/tsSIPrimeTSDescriptor.cpp, src/libtsduck/dtv/descriptors/isdb/tsSeriesDescriptor.cpp, src/libtsduck/dtv/signalization/tsPSIBuffer.h
<!--
Please read the TSDuck contribution guidelines for pull requests:
https://tsduck.io/download/docs/tsduck-dev.html#chap-contribution
Safer and more readable to use already defined names (more consistent too)
(Something else has broken Windows CI)
=> use defined constants for full length and short length modified Julian dates

src/tsplugins/tsplugin_mux.cpp
The current mux plugin does not generate transport stream with accurate bitrate.
The only change I made is on `tsplugin_mux.cpp`.
I set the `_pid_next_pkt` to be more accurate by calculate it on the fly. Rather than fixing an `_inter_pkt` that pre determined and truncated to the nearest integer, so It will make the resulted bitrate far from the target bitrate.
=> tsplugin_mux update

src/libtsduck/dtv/descriptors/dvb/tsComponentDescriptor.cpp
The component_type bitwise analysis it not related to the component_tag value
=> Reorder output to NGA features component descriptor 

CHANGELOG.txt, doc/user/plugins/scrambler.adoc, src/tsplugins/tsplugin_scrambler.cpp
#1566 
tsplugin_scrambler
When the `scrambler` plugin is used with a targeted service, this PL allows the user to only apply scrambling on a single elementary stream: `--only-pid`.
This is particularly useful to ensure the elementary streams are scrambled using individual control words.
Since the `scrambler` plugin is still targeting a service, unlike with the use of the `--pid` option, the PMT is used which allows the crypto-period and ECM scheduling to be enabled (see the related issue for details).
=> Add the --only-pid option to only scramble one component per service

.github/workflows/address-sanitizer.yml, .github/workflows/code-coverage.yml, .github/workflows/codeql-analysis.yml, .github/workflows/flawfinder-analysis.yml
Use Ubuntu 24.04 as for CI runner execution while update is "rolling out"
Update relevant CodeQL actions.
Still an issue in the "Coverage" ci related to building ` tsduck.tables.model.xml`
=> Use updated versions of CI dependencies

src/libtscore/tsVersion.h, src/libtsduck/dtv/descriptors/dvb/tsCPCMDeliverySignallingDescriptor.cpp
Ensure that both the window_start and window_end times are specified. 
See clause 5.4.5 of ETSI TS 102 825-4
=> both start and end times are needed to define the viewing window

src/libtsduck/dtv/codec/tsCodecType.cpp, src/libtsduck/dtv/codec/tsCodecType.h, src/libtsduck/dtv/signalization/tsStreamType.cpp, src/libtsduck/dtv/signalization/tsStreamType.h, src/libtsduck/dtv/signalization/tsStreamType.names
Add the supporting stream type (0xD2) for AVS2 coded video in an MPEG transport stream.
Samples are available at https://github.com/xatabhk/avs2-avs3-video-samples., although the `registration_descriptor` for AVSV should be in the outer (PMT) descriptor loop rather than the inner (ES) descriptor loop (see [北京冬奧片花_Beijing 2022 winter olympics emblem_640x360_avs2.ts](https://github.com/xatabhk/avs2-avs3-video-samples/raw/refs/heads/master/TS/%E5%8C%97%E4%BA%AC%E5%86%AC%E5%A5%A7%E7%89%87%E8%8A%B1_Beijing%202022%20winter%20olympics%20emblem_640x360_avs2.ts)
=> add support for AVS2 video tracks - in MPEG TS only

src/libtsduck/dektec/private/tsDektec.h
At least with GCC 14.2.0.
This will fail to compile with `-Werror`.
=> tsDekTec: disable some warnings when including DTAPI.h

src/libtsduck/dtv/broadcast/linux/tsTunerDevice.cpp, src/libtsduck/dtv/broadcast/tsModulationArgs.cpp
#1275
dvb (input)
Add sending a port-group 1 command, followed by a 100ms delay, and move the tone-burst command after the port-group 0 command.
This lines up with the DisEqC bus specification sections 5.3 and 5.4.
satellite-number is now in the range 0..63. The DiSEqC 1.1 switch moves on every four satellite-numbers, and a cascaded DisEqC 1.0 switch then moves on within those four satellite numbers.
If no suitable switch is present, then the command is ignored.
Testing:
The receiver was attached to a SPAUN SUR420 WSG DiSEqC 1.1 switch, set to mode 1;
1. port 1 had a voltage indicator attached;
2. port 2 had a DS-04C DiSEqC 1.0 switch, with voltage indicators on: lnb1; lnb2; and lnb3.
3. ports 3 and 4 were not connected.
Attempts were made to tune to:
* no defined satellite number (spaun …
=> Add control of DiSEqC 1.1 (uncommited) switch

src/libtsduck/dtv/descriptors/mpeg/tsVVCVideoDescriptor.names
Add additional descriptive names for the `profile_idc` element in the MPEG defined `VVC_video_descriptor`.
These values can be found in Annex A of the latest VVC standard - [ITU-T H.266 (V3) (09/2023)](https://www.itu.int/rec/T-REC-H.266-202309-I).
=> additional profile_idc values for VVC 
